### ISSUE TITLE
what is inefficient presentation mode?

### ISSUE THREAD

**Issue by ghost** [BoringBoredom/Frame-Time-Analysis#2]
Hello, I'm trying to learn about frame time and latency optimization so I started collecting data first, the game I collected data from was League of Legends and I wanted to test the analyzer on the GitHub page, but I see a warning about inefficient presentation mode, it says exactly ```Hardware Composed: Independent Flip, Composed: Flip``` What is it and how can I solve this? Thanks.

**Comment by BoringBoredom** [comment]
`Composed: Flip` is considered inefficient because it's buffered/v-synced. The presence of more than one presentation mode means it changed while you were recording the trace. You probably alt-tabbed.

**Comment by ghost** [comment]
@BoringBoredom yeah i alt-tabbed, but how can i change the composed flip? I did not open the vsync on league of legend's settings, but gsync is enabled on nvidia control panel, even though my monitor is 165hz fps was like 200+ so dunno

**Comment by BoringBoredom** [comment]
Don't alt-tab while recording.
